language: java
sudo: false

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

before_script:
  - mysql -e 'create database myscluscon_test;'

after_success:
  - mvn jacoco:report coveralls:report